### ISSUE TITLE
pycalcRecord fails build with base 3.15.9 (Ubuntu 22.04)

### ISSUE THREAD

**Issue by Sibelius8885** [klemenv/PyDevice#34]
I'm trying to build my Ioc using PyDevice but when I try to do it using the 3.15.9 base I get a series of errors:

/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE          -D_X86_64_ -DUNIX  -Dlinux     -O3   -Wall    -I/usr/include/python3.10 -I/usr/include/python3.10 -std=c++11 -O2 -DUSE_TYPED_RSET  -mtune=generic    -m64 -fPIC -g -ggdb -O0 -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/gcc -I../../include/os/Linux -I../../include -I/home/flyeye/Epics/base-3.15.9/include/compiler/gcc -I/home/flyeye/Epics/base-3.15.9/include/os/Linux -I/home/flyeye/Epics/base-3.15.9/include        -c ../pycalcRecord.cpp
../pycalcRecord.cpp: In function ‘void processRecordCb(pycalcRecord*)’:
../pycalcRecord.cpp:172:139: error: no matching function for call to ‘Variant(char*&, unsigned int&)’
  172 | ret_cast<   epicsInt8*>(*val); args["pydev"+field] = Variant(a, *ne); }
      |                                                                    ^

In file included from ../pywrapper.h:9,
                 from ../pycalcRecord.cpp:28:
../variant.h:78:5: note: candidate: ‘Variant::Variant(const unsigned char*, size_t)’ (near match)
   78 |     Variant(const unsigned char* vals,          size_t n) : Variant(std::vector<unsigned long long int>(vals, vals+n)) {};
      |     ^~~~~~~
../variant.h:78:5: note:   conversion of argument 1 would be ill-formed:
../pycalcRecord.cpp:172:133: error: invalid conversion from ‘char*’ to ‘const unsigned char*’ [-fpermissive]
  172 | ret_cast<   epicsInt8*>(*val); args["pydev"+field] = Variant(a, *ne); }
      |                                                              ^
      |                                                              |
      |                                                              char*

In file included from ../pywrapper.h:9,
                 from ../pycalcRecord.cpp:28:
../variant.h:73:5: note: candidate: ‘Variant::Variant(const signed char*, size_t)’ (near match)
   73 |     Variant(const signed char* vals,            size_t n) : Variant(std::vector<long long int>(vals, vals+n)) {};
      |     ^~~~~~~
../variant.h:73:5: note:   conversion of argument 1 would be ill-formed:
../pycalcRecord.cpp:172:133: error: invalid conversion from ‘char*’ to ‘const signed char*’ [-fpermissive]
  172 | ret_cast<   epicsInt8*>(*val); args["pydev"+field] = Variant(a, *ne); }
      |                                                              ^
      |                                                              |
      |                                                              char*

make[2]: *** [/home/flyeye/Epics/base-3.15.9/configure/RULES_BUILD:243: pycalcRecord.o] Error 1
make[2]: Leaving directory '/home/flyeye/Epics/base-3.15.9/PyDevice-main/src/O.linux-x86_64'
make[1]: *** [/home/flyeye/Epics/base-3.15.9/configure/RULES_ARCHS:58: install.linux-x86_64] Error 2
make[1]: Leaving directory '/home/flyeye/Epics/base-3.15.9/PyDevice-main/src'
make: *** [/home/flyeye/Epics/base-3.15.9/configure/RULES_DIRS:85: src.install] Error 2

The funny thing is that using the 7.0.7 base I was able to build it without any problem.
Thank you in advance.

**Comment by klemenv** [comment]
I suspect this is due to EPICS 3.16/7 redefining epicsInt8 and friends. There has been some work done to accomodate this to work between 3.14 and 3.16, but not necessarily on 3.15. Could you maybe try to provide a patch?
